theme: osuny
_merge: deep
params:
  debug:
    productionUrl: https://www.la27eregion.fr
  default:
    index:
      taxonomies:
        display: true
        layout: inline
        show_name: true
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  i18n:
    active: true
    positions:
      - secondary
  search:
    active: true
    positions:
      - secondary
      - footer
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logo.svg"
  home:
    head:
      title: site
  persons:
    index:
      taxonomies:
        display: true
        layout: inline
        show_name: true
  projects:
    index:
      options:
        year: true
    share_links:
      enabled: true
      facebook: true
      linkedin: true
      twitter: true
  posts:
    index:
      options:
        categories: false
    single:
      meta:
        options:
          reading_time: false
          updated_at: false
    share_links:
      enabled: true
      facebook: true
      linkedin: true
      twitter: true
  seo:
    title:
      separator: "•"
  image_sizes:
    _default:
      layouts:
        list:
          mobile:   360
          tablet:   555
          desktop:  864
        grid:
          desktop:  864